### ISSUE TITLE
Italian translation

### ISSUE THREAD

**Issue by lucamp** [msal/muzei-nationalgeographic#6]
Hi,
I would like to translate the menu in Italian, my mother tongue.
How can I help you?

Sincerely
Luca

**Comment by msal** [comment]
As the [main app](https://github.com/romannurik/muzei) doesn't include localization, I think that localized plugins might confuse the user. Hence I'd rather not include an Italian translation.
However, thanks a lot for the offer!

Your issue also reminded me, that this plugin already includes one single localization: Serbian. To keep it consistent, I will remove it.
